insert into adversarios (nome) 
values ('Sport Club Internacional'),
('Esporte Clube Vitória'),
('Cruzeiro Esporte Clube'),
('Mirassol Futebol Clube');

insert into competicoes (nome, temporada)
values ('Campeonato Brasileiro Série A', 2026),
('Copa Libertadores da América', 2026);

insert into jogadores (nome, data_nasc, nacionalidade, numero_camisa, posicao, altura, peso)
values ('Agustín Rossi', '1995-08-21', 'Argentina', 1, 'goleiro', 1.83, 92),
('Guillermo Varela', '1993-03-24', 'Uruguai', 2, 'defensor', 1.71, 69),
('Leo Ortiz', '1996-01-03', 'Brasil', 3, 'defensor', 1.85, 82),
('Léo Pereira', '1996-01-31', 'Brasil', 4, 'defensor', 1.86, 83),
('Erick Pulgar', '1994-01-15', 'Chile', 5, 'meio_campista', 1.86, 69),
('Ayrton Lucas', '1997-06-19', 'Brasil', 6, 'defensor', 1.80, 72),
('Luiz Araújo', '1996-06-02', 'Brasil', 7, 'atacante', 1.75, 69),
('Pedro', '1997-06-20', 'Brasil', 9, 'atacante', 1.85, 78),
('Giorgian de Arrascaeta', '1994-06-01', 'Uruguai', 10, 'meio_campista', 1.72, 69),
('Danilo', '1991-07-15', 'Brasil', 13, 'defensor', 1.84, 78),
('Jorge Carrascal', '1998-05-25', 'Colômbia', 15, 'meio_campista', 1.68, 74),
('Samuel Lino', '1999-12-23', 'Brasil', 16, 'atacante', 1.78, 72),
('Nicolás De La Cruz', '1997-06-01', 'Uruguai', 18, 'meio_campista', 1.67, 64),
('Gonzalo Plata', '2000-11-01', 'Equador', 19, 'atacante', 1.78, 76),
('Lucas Paquetá', '1997-08-27', 'Brasil', 20, 'meio_campista', 1.80, 72),
('Jorginho', '1991-12-20', 'Itália', 21, 'meio_campista', 1.80, 64),
('Emerson Royal', '1999-01-14', 'Brasil', 22, 'defensor', 1.81, 79),
('Alex Sandro', '1991-01-26', 'Brasil', 26, 'defensor', 1.80, 78),
('Bruno Henrique', '1990-12-30', 'Brasil', 27, 'atacante', 1.84, 71),
('Vitão', '2000-02-02', 'Brasil', 44, 'defensor', 1.86, 82),
('Evertton Araújo', '2003-02-28', 'Brasil', 52, 'meio_campista', 1.84, 73),
('Johnny Góes', '2007-03-27', 'Brasil', 77, 'defensor', 1.87, 68),
('Lorran', '2006-07-04', 'Brasil', 99, 'atacante', 1.80, 72);

insert into partidas (data_partida, mandante, gols_flamengo, gols_adversario, id_adversario, id_competicao) values
('2026-07-29', false, 1, 1, (SELECT id FROM adversarios WHERE nome = 'Sport Club Internacional'), (SELECT id FROM competicoes WHERE nome = 'Campeonato Brasileiro Série A')),
('2026-08-09', true, 2, 0, (SELECT id FROM adversarios WHERE nome = 'Esporte Clube Vitória'), (SELECT id FROM competicoes WHERE nome = 'Campeonato Brasileiro Série A')),
('2026-08-12', false, 1, 1, (SELECT id FROM adversarios WHERE nome = 'Cruzeiro Esporte Clube'), (SELECT id FROM competicoes WHERE nome = 'Copa Libertadores da América')),
('2026-08-16', false, 5, 1, (SELECT id FROM adversarios WHERE nome = 'Mirassol Futebol Clube'), (SELECT id FROM competicoes WHERE nome = 'Campeonato Brasileiro Série A')),
('2026-08-19', true, 2, 1, (SELECT id FROM adversarios WHERE nome = 'Cruzeiro Esporte Clube'), (SELECT id FROM competicoes WHERE nome = 'Copa Libertadores da América'));

insert into participacoes (id_partida, id_jogador, gols, assist, cartao) values
-- Partida vs Internacional (2026-07-29)
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Pedro'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Samuel Lino'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Giorgian de Arrascaeta'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Jorge Carrascal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Bruno Henrique'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Jorginho'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Nicolás De La Cruz'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Evertton Araújo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Erick Pulgar'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Alex Sandro'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Emerson Royal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Léo Pereira'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Danilo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Vitão'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Guillermo Varela'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-07-29'), (SELECT id FROM jogadores WHERE nome = 'Agustín Rossi'), 0, 0, NULL),

-- Partida vs Esporte Clube Vitória (2026-08-09)
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Pedro'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Bruno Henrique'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Samuel Lino'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Gonzalo Plata'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Giorgian de Arrascaeta'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Lucas Paquetá'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Jorge Carrascal'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Lorran'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Jorginho'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Evertton Araújo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Erick Pulgar'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Ayrton Lucas'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Léo Pereira'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Leo Ortiz'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Guillermo Varela'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-09'), (SELECT id FROM jogadores WHERE nome = 'Agustín Rossi'), 0, 0, NULL),

-- Partida vs Cruzeiro (2026-08-12)
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Bruno Henrique'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Pedro'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Samuel Lino'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Jorge Carrascal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Giorgian de Arrascaeta'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Lucas Paquetá'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Gonzalo Plata'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Guillermo Varela'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Jorginho'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Erick Pulgar'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Ayrton Lucas'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Léo Pereira'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Leo Ortiz'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Emerson Royal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-12'), (SELECT id FROM jogadores WHERE nome = 'Agustín Rossi'), 0, 0, NULL),

-- Partida vs Mirassol (2026-08-16)
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Pedro'), 2, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Gonzalo Plata'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Jorginho'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Jorge Carrascal'), 1, 2, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Luiz Araújo'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Samuel Lino'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Lucas Paquetá'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Giorgian de Arrascaeta'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Erick Pulgar'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Evertton Araújo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Ayrton Lucas'), 0, 1, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Johnny Góes'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Léo Pereira'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Danilo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Guillermo Varela'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-16'), (SELECT id FROM jogadores WHERE nome = 'Agustín Rossi'), 0, 0, NULL),

-- Partida vs Cruzeiro (2026-08-19)
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Pedro'), 0, 2, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Bruno Henrique'), 0, 0, 'amarelo'),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Samuel Lino'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Giorgian de Arrascaeta'), 1, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Lucas Paquetá'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Gonzalo Plata'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Jorge Carrascal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Jorginho'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Evertton Araújo'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Erick Pulgar'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Ayrton Lucas'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Guillermo Varela'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Léo Pereira'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Leo Ortiz'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Emerson Royal'), 0, 0, NULL),
((SELECT id FROM partidas WHERE data_partida = '2026-08-19'), (SELECT id FROM jogadores WHERE nome = 'Agustín Rossi'), 0, 0, NULL);